version: '3.3'

services:
  vps2_core:
    container_name: docker-12.2-core
    image: docker/12.2/core
    restart: always
    build:
      dockerfile: ./Docker/Dockerfile
      context: .
    working_dir: /Application
    volumes:
      - .:/Application
    tmpfs:
      - /tmp/difference/fun
    command: ['/usr/bin/init']
    ports:
      - "5002:80"
      - "5003:443"
    networks:
      - difference-fun-network
networks:
  difference-fun-network:
    driver: bridge
